### ISSUE TITLE
Internal Server Error after installing ThePoser

### ISSUE THREAD

**Issue by JulianMartinez** [mantisbt-plugins/ThePoser#3]
We have Mantis running in our machine. Version is 1.2.5 and Schema is 183.
I followed Installation instructions and when I clicked on Install, browser went to white.
Using Firebug I realized that Error 500 was raised.

I have uploaded a piece of the log in following link: http://mural.uv.es/jumaru/error_log.txt

I hope we can clarify the reason I was not able to install the plugin.
Thanks

**Comment by snowyurik** [comment]
According to the log function http_content_headers() is missing in your installation. However, it exist in version 1.2.5 (as can be downloaded from here http://sourceforge.net/projects/mantisbt/files/mantis-stable/1.2.5/)

Can you check <mantis root folder>/core/http_api.php line 114 for this function?

If it does not exist - i suggest you to upgrade to latest version (1.2.17) or download 1.2.5 from archive and overwrite your files. (backup old files first, just in case)

If it exist - reason is different, and I can't reproduce the bug using mantis v1.2.5 from archive.. can you send me the code you have in this case? (only the code, without config_inc.php and uploaded files if you store em in filesystem)
my email is yuriy@vihv.org

**Comment by JulianMartinez** [comment]
Line 114 on http_api.php looks normal:
function http_content_headers() {
    if ( !headers_sent() ) {
        header( 'Content-Type: text/html; charset=utf-8' );
        # For Internet Explorer 8 as per http://blogs.msdn.com/ie/archive/2008/07/02/ie8-security-part-v-comprehensive-protection.aspx
        # Don't let IE second guess our content-type!
        header( 'X-Content-Type-Options: nosniff' );
    }
}

I will send you the email with the code.

**Comment by snowyurik** [comment]
Reproduced and fixed, please update ThePoser
