### ISSUE TITLE
Error with SOAP

### ISSUE THREAD

**Issue by elpoutro** [mantisbt-plugins/ThePoser#4]
ThePoster work fine but there is an error 500 when i try to access mantis from Squash SC (http://www.squashtest.org):

"PHP Fatal error:  require_once(): Failed opening required 'core/http_api.php' (include_path='{URL to Mantis}/mantis/core/:{URL to Mantis}/mantis/library:../../library') in {URL to Mantis}/mantis/plugins/ThePoser/ThePoser.php on line 2"

Squash SC using SOAP: 
All requestes come from "{URL to Mantis}/api/soap/" and ThePoser.php try to include 'core/http_api.php' from "{URL to Mantis}/api/soap/core/http_api.php" on ThePoser.php line 2:
"require_once 'core/http_api.php';"

Just replace this line by this one and SOAP will work fine:
"$t_mantis_dir = dirname( dirname( dirname( **FILE** ) ) ) . DIRECTORY_SEPARATOR;
require_once $t_mantis_dir.'core/http_api.php';"

**Comment by snowyurik** [comment]
Thanks for report, I think I should find the way to disable ThePoser in case of soap request. 
Whatever, i'll upload bugfix tomorrow, or the day after tomorrow ether yours or mine.

**Comment by snowyurik** [comment]
Fixed (using your solution)
