### ISSUE TITLE
Support Mantis 1.3.x

### ISSUE THREAD

**Issue by pshentsoff** [mantisbt-plugins/ThePoser#5]
Is there plans for append support of Mantis version 1.3.x?

**Comment by snowyurik** [comment]
Sure, but latest release is 1.2.17.. so our plan is to wait for 1.3.0 stable.
(1.3.0 stable might be very differenent from 1.3.0 current nightly build)

However, if you want it right now - you can sponsor ThePoser for any version you need.
Right now it will cost only 80usd. And we can mention you on our website as a sponsor, like:
"Sponsored versions: 
Download ThePoser for MantisBT v1.3.0.91242cd (sponsored by V.Pshentsov http://v.pshentsov's.website)"

**Comment by pshentsoff** [comment]
Thank you for an early reply.
Seeing that most plugins while also support only a stable version of the Mantis core, I also downgraded to it.
