### ISSUE TITLE
Supported version

### ISSUE THREAD

**Issue by pshentsoff** [mantisbt-plugins/ThePoser#6]
Please, add to the README information about supported version of Mantis.

**Comment by andersruneson** [comment]
Please do, I tried installing on 1.2.10 but was missing the function http_is_protocol_https(), so this plugin failed to load and my mantis installation did not work until I removed the plugin.

**Comment by snowyurik** [comment]
it should work up to current release so 1.2.0 - 1.2.17 .
So, this is a bug.  So i'm going to fix it in a few days.

**Comment by snowyurik** [comment]
"1.2.10 missing the function http_is_protocol_https()" issue fixed, please try
